### PR TITLE
Improve FAPI tests when using a virtual TPM device

### PR DESCRIPTION
**Pull request by rosslagerwall**
This PR reduces the number of failures when running against a device. In particular, when running in a VM against a virtual TPM device provided by swtpm.

Before this PR, there were 54 failures. After this PR, there are 10 failures. I haven't yet investigated the remaining failures.

### CODE REVIEW

**Comment by JuergenReppSIT** [comment]
@rosslagerwall With the attached format patch all the tests should work. In the integration test with Fapi_ExportPolicy for a policy which was created with Fapi_Import the policy digests were computed for all hash algs defined in the profiles. Because you added a sha384 profile the check had to be adapted.
[0001-fix-json-check.zip](https://github.com/tpm2-software/tpm2-tss/files/9630591/0001-fix-json-check.zip)

**Comment by JuergenReppSIT** [comment]
@rosslagerwall Thank you for testing the fapi with the sha384 profile with a virtual TPM.
I could reproduce the remaining 9 fails on qemu. For 5 test cases I found a solution and I will investigate the remaining 4.

**Comment by JuergenReppSIT** [comment]
@rosslagerwall To resolve the problem with the failing test I have added  your P_ECC384 profile, with the fixed test to master.
Could you please rebase your PR and solve the merge conflict caused by test/data/fapi/P_ECC384.json.

**Comment by rosslagerwall** [comment]
Thanks @JuergenReppSIT, I've rebased and the CI tests pass now.

Also thanks for looking at the remaining failures, will you be able to send a PR for that?

**Comment by JuergenReppSIT** [comment]
@rosslagerwall Very good. Thank you also for the fixes related to the templates from the high range.
 In the meantime I have adapted the tests to the usage of the P_ECC384 profile. I will create a
PR after your PR is merged. So no failures should occur with a virtual TPM device using curveID TPM2_ECC_NIST_P384.

**Review by JuergenReppSIT — APPROVED** [review]

**Pull request merged**
