### PR TITLE
ESAPI: remove nonceTPM parameter according to ESAPI specification

### PR DESCRIPTION
**Pull request by IKhanov**
See #2515.

Signed-off-by: Ilya Khanov <ilya.khanovvv@gmail.com>

### CODE REVIEW

**Review by williamcroberts — APPROVED** [review]

**Comment by williamcroberts** [comment]
This will bump soname to 1.0.0

**Comment by williamcroberts** [comment]
> @AndreasFuchsTPM not sure if we want to drop this parameter or support NULL and update the spec. This would have impact on systemd.

Actually this doesn't affect systemd, I'm they dont use these APIs

**Review by JuergenReppSIT — APPROVED** [review]

**Comment by AndreasFuchsTPM** [comment]
See my comment https://github.com/tpm2-software/tpm2-tss/issues/2515#issuecomment-1348871765

I would be against a merge and a quick update to the TCG specs (removal of headers).

**Review by williamcroberts — CHANGES_REQUESTED** [review]
After the lengthy discussion on the issue ticket it was decided we wanted the caller to retain control of this input parameter

**Pull request closed without merging**
