### PR TITLE
util: mark variables as unused

### PR DESCRIPTION
**Pull request by tstruk**
Mark some variables are always unused.
They are not used in nether debug nor logging statements.

### CODE REVIEW

**Comment by williamcroberts** [comment]
This is just one part of the PR. Plus you didn't update the doxygen comments on paramters. Use PR #2050

**Comment by williamcroberts** [comment]
Theirs also fixes on PR 2051 that fix some issues in the test code that was hidden by MAYBE_UNUSED, as well as removes the need for NDEBUG, among other changes

**Comment by tstruk** [comment]
will go with #2050

**Comment by williamcroberts** [comment]
> will go with #2050

No, this has the other fixes in it. Plus I found other cases of (void) in the fapi code that needs more removals.

**Pull request closed without merging**
