### PR TITLE
Now we have consistent prefix names for ESAPI and SAPI. Fix #998

### LINKED ISSUE #998: Consistent names in test harness
ESAPI tests use 'esys' in some places and 'esapi' in others for test prefix. SAPI uses 'sapi'.
This should be renamed to 'esys' and 'sys'.

### PR DESCRIPTION
**Pull request by manuknz**
We used to have 'ESAPI' and 'SAPI' prefix names in some places and 'ESYS' and 'SYS' in anothers. So changes were made to some filenames and the sourcecode of other files themselves, this to keep the prefix names consistent to 'SYS' for 'SAPI' and 'ESYS' for 'ESAPI' .

### CODE REVIEW

**Comment by tstruk** [comment]
I like this idea of making the prefix consistent. There are some issues with the PR that needs to be resolved first:
Please git reset --hard HEAD~2 and push --force to get rid of the two top commits.
There are some build issues in cirrus that need to be addressed:
https://github.com/tpm2-software/tpm2-tss/pull/1755/checks?check_run_id=755739345
I can take the commit 2 as is. Thanks for that cleanup.
Commit three probably belongs to a separate PR.

**Comment by manuknz** [comment]
Finished changing the commits, I'll look into the issues with cirrus. Thanks for the feedback @tstruk

**Comment by manuknz** [comment]
I've dropped the commit 3 as you suggested. I’ve also rebased my branch on top of latest master and verified that there are no conflicts. Now everything should be good to go. @tstruk

**Comment by tstruk** [comment]
@manuknz could you resolve the conflicts please

**Comment by tstruk** [comment]
@manuknz I resolved the conflict, but now the github GUI hanged. Could you just pull and then push again to unblock it.

**Comment by manuknz** [comment]
Sorry, yesterday I was a little busy and couldn't look at the conflicts. You want me to pull the lastest version of the master and then push it to my fork? @tstruk

**Comment by tstruk** [comment]
That's a good question. I resolved the conflict using the github gui, and it created a commit (https://github.com/tpm2-software/tpm2-tss/pull/1755/commits/d8efaf88345eb11bcdf203dd9c2d33c69c381968) somewhere, but I have no idea where. I think the best way to solve it will be if you solve the conflict yourself (it's trivial) and the force push to your branch.

**Comment by manuknz** [comment]
Gotcha. I’ll resolve the conflict then and push again. Thanks a lot for your help @tstruk

**Comment by manuknz** [comment]
Done, everything looking good now. @tstruk

**Pull request merged**
