### PR TITLE
esys: add a new function to retrieve sys context from esys

### PR DESCRIPTION
**Pull request by tstruk**
In some cases it can be necessary to call the underlining
sys function before invoking esys function. One example
would be to retrieve cpHash buffer of a command that needs
to be fed to Esys_PolicySigned or Esys_PolicySecret calls.
This can be done by using the Tss2_Sys_GetCpBuffer()
sys call as long as the user can access the sys context.
That's one possible (and simple) solution.
See issue: #1533

### CODE REVIEW

**Comment by tstruk** [comment]
> I still prefer the tcti-less syscontext approach.
> Reason is that this change will bind ESYS to SYS forever. We will never be able to ditch SYS and only provide ESYS without breaking API; nor will anybody else...

That is true, but will there ever be ESYS without SYS? Isn't it already bind forever by all the diagrams like in [1], where ESYS box is always above SYS box.

[1] Esys spec - https://trustedcomputinggroup.org/wp-content/uploads/TSS_TSS-2.0-Enhanced-System-API_V0.9_R03_Public-Review-1.pdf

**Comment by AndreasFuchsSIT** [comment]
> > I still prefer the tcti-less syscontext approach.
> > Reason is that this change will bind ESYS to SYS forever. We will never be able to ditch SYS and only provide ESYS without breaking API; nor will anybody else...
> 
> That is true, but will there ever be ESYS without SYS? Isn't it already bind forever by all the diagrams like in [1], where ESYS box is always above SYS box.

That diagram is just informative... This change would make this binding normative.

**Comment by tstruk** [comment]
@AndreasFuchsSIT if we ever implement SYS-less ESYS then we will need to add a bunch of new functions like the mentioned Esys_getCpHash etc, and after we have that we could change Esys_GetSysContext() to always return NULL sys context, indicating that this ESYS is SYS-less.

**Comment by tstruk** [comment]
@idesai do you have any feedback on this?

**Comment by AndreasFuchsSIT** [comment]
LGTM

**Pull request merged**
