### PR TITLE
2.1.4 rc1

### PR DESCRIPTION
**Pull request by AndreasFuchsSIT**

### CODE REVIEW

**Comment by flihp** [comment]
Apologies for the ignorance here but are we not supporting the windows build on the 2.x branch? From your comment above it seems to be common knowledge that the AppVeyor build doesn't work but I can't tell if this is intentional or if it's something that you and @tstruk discussed before he left.

**Comment by AndreasFuchsSIT** [comment]
Yes, we decided to not fix AppVayor-CI for the (old) 2.1.x branch for now (given priorities).
If you find the time, I'll gladly merge it. Just tell me, and I'll postpone rc1 until you got a fix.

**Comment by flihp** [comment]
This was just a cherry-pick. PR is open: #1409

**Comment by AndreasFuchsSIT** [comment]
Updated rebased to #1409 
Let's see if that does the trick, then I'll release...

**Pull request merged**
