### PR TITLE
Fix for Tpm2b marshaling code

### PR DESCRIPTION
**Pull request by tstruk**
Fixes an issue found during fuzzing

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
If there is any kind of padding, I think sizeof(*dest) could be larger than sizeof(dest->size) + sizeof(dest->buffer).

But I understand that the buffer-field is not allways called buffer, but something else. Maybe we would add a parameter to the makros for the buffername or similar ?

**Comment by tstruk** [comment]
The TPM2B are always size UINT16 and buffer BYTE[]
There is no padding in any of them so sizeof(*dest) will never be larger than sizeof(dest->size) + sizeof(dest->buffer). Or more specifically - sizeof(*dest) - 2 will always be equal to sizeof(dest->buffer_name).
As you said the buffer itself is called differently in different structures, but I don't see a need for an extra param.

**Comment by tstruk** [comment]
To make sure I just checked that with pahole, and for instance:
        /* typedef TPM2B_DATA */ struct {
                /* typedef UINT16 -> uint16_t -> __uint16_t */ short unsigned int size;  /* 2 */
                /* typedef BYTE -> uint8_t -> __uint8_t */ unsigned char      buffer[64]; /* 64 */
        } /* 66 */

/* typedef TPM2B_SENSITIVE_CREATE */ struct {
        /* typedef UINT16 -> uint16_t -> __uint16_t */ short unsigned int size; /* 2 */
        /* typedef TPMS_SENSITIVE_CREATE */ struct {
               /* typedef TPM2B_AUTH -> TPM2B_DIGEST */ struct {
                       /* typedef UINT16 -> uint16_t -> __uint16_t */ short unsigned int size; /* 2 */
                       /* typedef BYTE -> uint8_t -> __uint8_t */ unsigned char  buffer[64]; /* 64 */
                                 } userAuth; /* 66 */
                                 /* typedef TPM2B_SENSITIVE_DATA */ struct {
                                        /* typedef UINT16 -> uint16_t -> __uint16_t */ short unsigned int size; /* 2 */
                                        /* typedef BYTE -> uint8_t -> __uint8_t */ unsigned char  buffer[256]; /* 256 */
                                } data; /* 258 */
                   } sensitive; /* 324 */
   }; /* 326 */

That's for gcc and clang.

**Comment by tstruk** [comment]
Actually TPM2B_PUBLIC does have padding. Given that and that this is compiler specific I think adding an extra param 'buf_name' and using it in the sizeof() keeps us on the safe site. A new PR on the way.

**Pull request merged**
