### PR TITLE
Compute session fixes

### PR DESCRIPTION
**Pull request by tstruk**

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
There's a typo in your commit message... ;-)

**Comment by tstruk** [comment]
> There's a typo in your commit message... ;-)
Fixed :)

**Comment by AndreasFuchsSIT** [comment]
@tstruk I guess we need to backport too, right ?

**Comment by tstruk** [comment]
@AndreasFuchsSIT yes, I will cherry pick it to 2.3.x branch and tag a new release

**Comment by AndreasFuchsSIT** [comment]
@tstruk I guess we should pick #1590 for that as well. However I had no time investigating... :-(

**Pull request merged**
