### PR TITLE
event log permissions

### PR DESCRIPTION
**Pull request by whooo**
Use tpm2-tss-fapi.conf to set permissions for UEFI and IMA events logs in sysfs.
Works well on my laptop.

Fixes https://github.com/tpm2-software/tpm2-tss/issues/2446

### CODE REVIEW

**Comment by JuergenReppSIT** [comment]
> Use tpm2-tss-fapi.conf to set permissions for UEFI and IMA events logs in sysfs.
> Works well on my laptop.
I wanted the group assignment to remain intact over the boot cycle. Therefore during experimenting I did copy the described tmp file config to /lib/tmpfile.d/. After the reboot the group assignment was only set for the ima files. Therefore I decided to create the one shot service. With your solution after the reboot the files are still owned by root.root.
So the tmp file config solution works only for `make install`.

**Comment by williamcroberts** [comment]
This seems related to:
  - https://github.com/tpm2-software/tpm2-tss/issues/2451

However, I see the fix and keeping the oneshot service as we need something to run on every boot. I guess we gotta figure out why this fails in our ci

**Comment by whooo** [comment]
> > Use tpm2-tss-fapi.conf to set permissions for UEFI and IMA events logs in sysfs.
> > Works well on my laptop.
> 
> @whooo I wanted the group assignment to remain intact over the boot cycle. Therefore during experimenting I did copy the described tmp file config to /lib/tmpfile.d/. After the reboot the group assignment was only set for the ima files. Therefore I decided to create the one shot service (Did work without problems on Ubuntu 20.04). With your solution after the reboot the files are still owned by root.root. So the tmp file config solution works only for `make install`.

On the same machine, do you have another file named tpm2-tss-fapi.conf under /etc/tmpfiles.d/ without the event log paths?

**Comment by JuergenReppSIT** [comment]
> On the same machine, do you have another file named tpm2-tss-fapi.conf under /etc/tmpfiles.d/ without the event log paths?

yes there was another file. Now it works also after reboot.
@whooo  Thank you!

**Review by JuergenReppSIT — APPROVED** [review]

**Pull request merged**
