### PR TITLE
ci: add CIFuzz integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which tpm2-tss already runs.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
I am not too sure if we want this on every PR or just on merges into master... Seems too much to me...
@williamcroberts thoughts ?

**Comment by williamcroberts** [comment]
> I am not too sure if we want this on every PR or just on merges into master... Seems too much to me... @williamcroberts thoughts ?

I'd run this with every PR to help catch regressions that get missed in typical testing. AFAICT it doesn't cost us anything or needlessly slow the CI, so I am in favor of adding it. I actually integrated fuzzing tests into PKCS11 with `--enable-fuzzing` and run it as part of my CI.

The fact that this is integrated with OSS fuzz seems nice, as it only flunks people for new failures, granted we don't have old failures. I like this a ton, although it's not clear to me whos server it's running on (is it triggering an OSS Fuzz server and reporting back, or it it running on GH and just querying OSS Fuzz).

**Comment by DavidKorczynski** [comment]
> The fact that this is integrated with OSS fuzz seems nice, as it only flunks people for new failures, granted we don't have old failures. I like this a ton, although it's not clear to me whos server it's running on (is it triggering an OSS Fuzz server and reporting back, or it it running on GH and just querying OSS Fuzz).

I believe it's running on the OSS-Fuzz server. @jonathanmetzman can you confirm this?

**Comment by jonathanmetzman** [comment]
> > The fact that this is integrated with OSS fuzz seems nice, as it only flunks people for new failures, granted we don't have old failures. I like this a ton, although it's not clear to me whos server it's running on (is it triggering an OSS Fuzz server and reporting back, or it it running on GH and just querying OSS Fuzz).
> 
> I believe it's running on the OSS-Fuzz server. @jonathanmetzman can you confirm this?

CIFuzz fuzzes in your CI, not on OSS-Fuzz.
The only interaction it has with CIFuzz is downloading the (public) corpus and coverage data.

**Pull request merged**
