### PR TITLE
Fix curl uaf

### PR DESCRIPTION
**Pull request by williamcroberts**
Fixes: #2523

Note we could even add an assert to doLogBuf so debug builds will abort.

### CODE REVIEW

**Review by JuergenReppSIT — APPROVED** [review]
@williamcroberts Thank you for fixing the issue assigned to me. Sorry I just saw it.

**Comment by williamcroberts** [comment]
> @williamcroberts Thank you for fixing the issue assigned to me. Sorry I just saw it.

No problem, it was assigned to me too :-p

**Review by AndreasFuchsTPM — APPROVED** [review]
I like it

**Comment by AndreasFuchsTPM** [comment]
I guess we need to backport this as well ?

**Comment by williamcroberts** [comment]
> I guess we need to backport this as well ?

Back ported on 3.2.x:
https://github.com/tpm2-software/tpm2-tss/pull/2526

**Comment by williamcroberts** [comment]
> I guess we need to backport this as well ?

Nope, 3.2.x doesn't suffer from this as `fapi_crypto.c:ifapi_verify_ek_cert` doesn't attempt to log it, it just goto's a cleanup label.

**Pull request merged**
