### PR TITLE
build: Fix failed build with --disable-vendor

### PR DESCRIPTION
**Pull request by JuergenReppSIT**
The compilation of the marshaling functions for TPML_INTEL_PTT_PROPERTY is now disabled for builds with --disable-vendor.
Fixes: #2571

### CODE REVIEW

**Comment by gotthardp** [comment]
Thanks! There is one more `TPML_INTEL_PTT_PROPERTY` in `tss2-dlopen/tss2-dlopen-mu.c`. That can be left enabled, or could it be also a problem?

**Comment by JuergenReppSIT** [comment]
> Thanks! There is one more `TPML_INTEL_PTT_PROPERTY` in `tss2-dlopen/tss2-dlopen-mu.c`. That can be left enabled, or could it be also a problem?

Thank you for the review. yes now I have checked all occurrences of INTEL_PTT.

**Review by gotthardp — APPROVED** [review]
It works for me. Thanks a lot!

**Comment by gotthardp** [comment]
Would you please backport this to 4.0.2 as well?

**Pull request merged**
