### PR TITLE
esys: don't print error msgs on expected errors

### PR DESCRIPTION
**Pull request by tstruk**
Fixes: #1573

### CODE REVIEW

**Comment by tstruk** [comment]
> Is this really something that we want to see applied to every TPM command ?
> I know we (Bill) want it for TestParams.
> But is RC_KEYSIZE maybe an actual error in some cases ?
That's why I'm looking for feedback on what we really want to suppress.
@williamcroberts what do you need for now? Let's start with minimum and then expand as needed.
I will also need to ad an else case with LOG_DEBUG() before it goes in.

**Comment by tstruk** [comment]
> LGTM. Surprised that macro expansion that declares a variable inside an if worked in older gcc version like 5 too.
Statement expressions are supported since gcc3 I think:
https://gcc.gnu.org/onlinedocs/gcc-3.2.3/gcc/Statement-Exprs.html

**Comment by tstruk** [comment]
@williamcroberts any comments on what we want to suppress?

**Comment by williamcroberts** [comment]
> @williamcroberts any comments on what we want to suppress?

I completely misread this patch. This actually appears to be filtering at every TSS/TPM command level, we only care about TestParams AFAICT.

We want to make this only for TestParams.

**Comment by williamcroberts** [comment]
I have a draft PR that addresses this:
https://github.com/tpm2-software/tpm2-tss/pull/1664

**Comment by tstruk** [comment]
Superseded by https://github.com/tpm2-software/tpm2-tss/pull/1664

**Pull request closed without merging**
