### PR TITLE
FAPI: Fix memory leak after ifapi_init_primary_finish failed

### PR DESCRIPTION
**Pull request by JerryDevis**

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
@JerryDevis Thanks a lot for you reviews. Seams like you are currently in a good process over the code base.
I wanted to a align with you, since I want to relase 3.2 pretty soon.
What is you status on things ? Does it make sense to wait a week or two ?

**Comment by JerryDevis** [comment]
> 

OK, I also look forward to a new version. You can relase 3.2 first. I push the insignificant PR after you relase 3.2.

**Comment by JerryDevis** [comment]
> @JerryDevis Thanks a lot for you reviews. Seams like you are currently in a good process over the code base. I wanted to a align with you, since I want to relase 3.2 pretty soon. What is you status on things ? Does it make sense to wait a week or two ?
OK, I also look forward to a new version. You can relase 3.2 first. I push the insignificant PR after you relase 3.2.

**Comment by AndreasFuchsSIT** [comment]
You got me wrong. I wanted to merge as much as possible before 3.2... :-)
I'll also happily merge this PR...

**Review by JuergenReppSIT — APPROVED** [review]

**Pull request merged**
