### PR TITLE
Fixed two TCG spec violations in the TSS library.

### PR DESCRIPTION
**Pull request by LordOfDorks**
Each description is listing the corresponding violation of the Rev 1.38 specs.

### CODE REVIEW

**Comment by tstruk** [comment]
@LordOfDorks thanks for the patch.
The fact the we don't support the latest addition to the spec doesn't mean that we violate it ;)
We strive for both API and ABI backwards compatibility within the same major number releases, as described in [1]. I'm not sure if for this change we will need to bump the major number to 3.x.y

[1] https://github.com/tpm2-software/tpm2-tss/blob/master/RELEASE.md#version-numbers

**Comment by AndreasFuchsSIT** [comment]
Having though about it: The ReadClock update to 1.38 can be handled as a two-stage approach. We can make the API/ABI compatible change now (setting the bits) so it is usable in the async scheme and from Esys.
We delay the API/ABI incompatible change for 1 release and give some deprecation warning in the next ?

**Comment by AndreasFuchsSIT** [comment]
Regarding the hmac-key calculation: Could you provide a test-case / seQuence that demonstrates the bug? Then we could add this test case to the integration test suite.

**Comment by AndreasFuchsSIT** [comment]
@LordOfDorks you just added two unrelated commits to this PR. Also they contain no commit message and not code comments.
Would you mind structuring this a bit into separate PRs with commit messages and more code comments ? Thanks!

**Pull request closed without merging**
