### PR TITLE
Remove SHA1 from tests

### PR DESCRIPTION
**Pull request by joholl**
This has proven very tricky. Due to the sheer amount of SHA1 use, I could not understand every test case in depth.

* Remove SHA1 (sometimes, I replaced SHA256 with SHA384 and SHA1 with SHA256 to keep code changes small)
* Update hashes where necessary
* Add comments where helpful
* Add graceful handling of `TPM2_RC_COMMAND_CODE` for three tests

Fixes: #2818
Fixes: #2862

### CODE REVIEW

**Comment by joholl** [comment]
Thanks, @JuergenReppSIT, fixed that.

I also fixed the `PolicyTemplate` calculation bug #2862 here, please make sure to review this, too. We will want to backport that.

**Comment by joholl** [comment]
Added a few commits for tpmclient. Now the test suite is SHA1-free for me.

Also saw a problem with tpmclient and libtpms. Fixed it, so now tpmclient can (actually) reset libtpms.

**Comment by AndreasFuchsTPM** [comment]
```
../test/tpmclient/tpmclient.int.c:661:39: runtime error: index 20 out of bounds for type 'BYTE [20]'
```

**Comment by JuergenReppSIT** [comment]
I have tested the PR with a physical TPM with the following findings:
* On pi3 (32bit) got the following compile error (was introduced with : https://github.com/tpm2-software/tpm2-tss/commit/3161afdf32943112505a478834b95fd287ccf3b4) `ret` which was declared as int was used instead of `rc` before.
 ```
src/tss2-tcti/tcti-mssim.c: In function ‘tcti_mssim_receive’:
src/tss2-tcti/tcti-mssim.c:408:12: error: comparison of integer expressions of different signedness: ‘TSS2_RC’ {aka ‘unsigned int’} and ‘int’ [-Werror=sign-compare]
  408 |     if (rc < (ssize_t)tcti_common->header.size) {
```
* Fapi failed if sha384 is not available. sha384 should only be used in the profiles where it was used before. In the other cases the sha1 bank could be removed from the profile.
* The test test/integration/policy-execute.c failed with:
 ```
WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:398:Esys_StartAuthSession_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:143:Esys_StartAuthSession() Esys Finish ErrorCode (0x000005c3)
ERROR:test:test/integration/policy-execute.int.c:722:check_policy() Error: During initialization of session ErrorCode (0x000005c3)
ERROR:test:test/integration/policy-execute.int.c:939:test_policy_execute() Checking policy digest for sha384 failed ErrorCode (0x000005c3)
ERROR:test:test/integration/main-esys.c:49:main() Test returned 00000001
 ```

**Comment by joholl** [comment]
CI is green now.

@AndreasFuchsTPM @JuergenReppSIT Feel free to review. Please note the digests which I just appended `0x00s`, I'm not sure if those test should be green.

**Review by AndreasFuchsTPM — APPROVED** [review]

**Pull request merged**
