### PR TITLE
RFC: add sphinx build for Read the Docs

### PR DESCRIPTION
**Pull request by joholl**
For easier access, the doxygen documentation could be hosted (and referenced by `README.md`).  Readthedocs is a really cool site but it does not support doxygen (only [sphinx](https://www.sphinx-doc.org)). Howver, you can create an empty sphinx project, make it generate the doxygen doc and include the html files.

I have an example hosted at [tpm2-tss.readthedocs.io](https://tpm2-tss.readthedocs.io/en/latest/). The build is completely automatic and is triggered by pushing a commit to a specific branch.

What do you think?

Note: Unfortunately the doxygen doc cannot be generated by make (readthedocs does not have autoconf). Instead, I had to convert `Doxyfile.in` to `Doxyfile` using `sed` and then call doxygen manually (see [here](https://github.com/tpm2-software/tpm2-tss/compare/master...joholl:enable_readthedocs?expand=1#diff-5820bd443376e6f878b54152642ea8aaR26)). Currently the doxygen version is `master`. The readthedocs version is `latest` since `master` cannot be set to a custom branch. We might change that later.

### CODE REVIEW

**Comment by joholl** [comment]
Travis is failing at one build because `apt-get install` failed. Not a bug.

**Comment by tstruk** [comment]
We probably need to add index.rst or README.rst that would point to https://tpm2-tss.readthedocs.io/en/latest/

**Comment by joholl** [comment]
I'd rather suggest hosting only the doxygen doc on Read the Docs. In the end, [tpm2-tss.readthedocs.io](https://tpm2-tss.readthedocs.io) will point to doxygen's `index.html` directly.

As I said, we probably want to have Read the Docs build the documentation for master which I cannot do at the moment since I am working on a feature branch. However, you can set the root page to whatever branch you wish (including master and latest which is an arbitrary branch).

**Comment by joholl** [comment]
At the moment an empty `index.rst` is created which does not come into account because the `index.html` by doxygen is used.

**Comment by joholl** [comment]
It's been a week now. My suggestion of going forward with this is first merging this PR and then setting up the Read the Docs account.

If you want, we can use my Read the Docs account and switch to master once you merged. Alternatively I can delete my account and release the now occupied domain *tpm2-tss.readthedocs.io* for you.

**Comment by tstruk** [comment]
> If you want, we can use my Read the Docs account and switch to master once you merged. Alternatively I can delete my account and release the now occupied domain _tpm2-tss.readthedocs.io_ for you.

I would prefer the later. Thanks

**Comment by joholl** [comment]
Done. If you have problems with setting up the account just let me know.

**Comment by tstruk** [comment]
The new tpm2-tss.readthedocs.io created and looks good. Thanks

**Pull request merged**
