### PR TITLE
ESYS: add Esys_TR_GetTPMHandle

### PR DESCRIPTION
**Pull request by williamcroberts**
Add routine Esys_TR_GetTpmHandle() which given an ESYS_TR retrieves the
TPM2_HANDLE which can be used with SAPI or for direct access to
handle values for comparisons or handle masks. Also, add tests.

Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
Looks good, but I'd prefer some other name like `Esys_TR_GetTpmHandle`
I know where your naming came from, but I don't think this applies here.

**Comment by williamcroberts** [comment]
> Looks good, but I'd prefer some other name like `Esys_TR_GetTpmHandle`
> I know where your naming came from, but I don't think this applies here.

Updated, thanks

**Comment by AndreasFuchsSIT** [comment]
For your convenience:
```
test/integration/test_integration_esys_tr_toTpmPublic_key_int-esys-tr-toTpmPublic-key.int.o: In function `test_esys_tr_toTpmPublic_key':

/workspace/tpm2-tss/build/../test/integration/esys-tr-toTpmPublic-key.int.c:113: undefined reference to `Esys_TR_GetTpmHandle'

/workspace/tpm2-tss/build/../test/integration/esys-tr-toTpmPublic-key.int.c:128: undefined reference to `Esys_TR_GetTpmHandle'
```

**Comment by AndreasFuchsSIT** [comment]
Will you rename the tests as well ?

**Comment by williamcroberts** [comment]
> Will you rename the tests as well ?

Definitely

**Pull request merged**
