### PR TITLE
Add OpenSSL dependency to INSTALL.md

### PR DESCRIPTION
**Pull request by DomiNic5787**

### CODE REVIEW

**Comment by DomiNic5787** [comment]
It is a test suite-only dependency, because it is only used by the test suite, isn't it?
If it is meant to only list unit test suite dependencies here, then it has to be mentioned in the description above.

**Comment by tstruk** [comment]
OpenSSL is only required for the integration tests, which is enabled by the --with-simulatorbin option

**Comment by DomiNic5787** [comment]
see #770

**Comment by flihp** [comment]
Good catch @DomiNic5787.

**Comment by flihp** [comment]
PR #771 resolves the the issue w/r to building libtest when the integration tests are disabled. Now a simple `./bootstrap && ./configure && make` should not require libcrypto or any of its headers. Still, the documentation needs a note added to indicate that libcrypto & headers are required when the integration tests are built (enabled with `--with-simulatorbin`).

I left the documentation fix out of my PR since this one is already open. @DomiNic5787: will you please fix up this PR accordingly?

**Comment by flihp** [comment]
thanks @DomiNic5787

**Pull request merged**
