### PR TITLE
Logging: Fix --with-maxloglevel

### PR DESCRIPTION
**Pull request by AndreasFuchsSIT**
The --with-loglevel configure switch was
not working. Renamed it and made it working
as --with-maxloglevel.
Also fixed an unused variable in tests for
maxloglevel==none.

Signed-off-by: Andreas Fuchs <andreas.fuchs@sit.fraunhofer.de>

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
@flihp Can you help me around the appveyor topic ?

**Comment by flihp** [comment]
VS fixups are here: https://github.com/flihp/tpm2-tss/commit/a413531f17c720c0cb0175f8d04d2732174ec664

**Comment by AndreasFuchsSIT** [comment]
@tstruk Thanks to @flihp seems to be working also for VisualStudio...

**Comment by AndreasFuchsSIT** [comment]
You mean the comments for the endifs ?

**Comment by flihp** [comment]
Yes.

**Comment by flihp** [comment]
whoops, I did something in the UI and nuked my comments. Looks like you already updated this anyways. Sorry ☹️

**Comment by AndreasFuchsSIT** [comment]
Good Point... Updated now (on 2nd attemt to push)...

**Comment by flihp** [comment]
Thanks for updating this. Much more clear now. I'll merge as soon as the CI passes.

**Pull request merged**
