### PR TITLE
doc: add markdown file about TCTIs

### PR DESCRIPTION
**Pull request by joholl**
Depends on #2646.

### CODE REVIEW

**Comment by joholl** [comment]
@JuergenReppSIT Ok, this is done now.

The only thing I could not verify is calling something like `tpm2_getrandom --tcti="cmd:ssh 192.168.178.123 tpm2_send --tcti='device:/dev/tpm0'"`to verify the ssh example.

**Comment by JuergenReppSIT** [comment]
> @JuergenReppSIT Ok, this is done now.
> 
> The only thing I could not verify is calling something like `tpm2_getrandom --tcti="cmd:ssh 192.168.178.123 tpm2_send --tcti='device:/dev/tpm0'"`to verify the ssh example.

@joholl  I could verify it with an 192.168.... address after i changed the group of the remote /dev/tpm0 to tss. With /dev/tpmrm0 it worked at once. So perhaps it would be better to use /dev/tpmrm0 in the examples to avoid problems if someone tries it out?

**Comment by joholl** [comment]
@JuergenReppSIT done :)

**Comment by Akuli** [comment]
I am new to TPM and I think this doc is awesome :)

**Review by JuergenReppSIT — APPROVED** [review]
Very good, thank you!

**Pull request merged**
