### PR TITLE
policy: add null checks on exec callbacks

### PR DESCRIPTION
**Pull request by williamcroberts**
Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Review by AndreasFuchsTPM — CHANGES_REQUESTED** [review]
That a bad bug here, so good that it's fixed.

I just don't like the return code. NOT_IMPLEMENTED would be something where the user-called function is not implemented.

Since we don't have a better return code, I'd vote for adding a new one; i.e. CALLBACK_MISSING or similar.

**Comment by williamcroberts** [comment]
> NOT_IMPLEMENTED would be something where the user-called function is not implemented.

This seems contradictory tot he fact you want a change, considering we are returning NOT_IMPLEMENTED where the user-called function is not implemented.

**Comment by AndreasFuchsTPM** [comment]
My rational is that when you call Fapi_Sign() and a "NOT_IMPLEMENTED" is returned, you might easily assume that Sign is not implemented or that a certain algorithm is not implemented, but the case of "the callback was not set" does not intuitively come to mind.

**Comment by williamcroberts** [comment]
@AndreasFuchsTPM or @JuergenReppSIT please review, thanks

**Pull request merged**
