### PR TITLE
travis: temporarily disable doxygen

### PR DESCRIPTION
**Pull request by tstruk**
Looks like Doxygen causes some builds problems on travis
Disable it for now until it is resolved.

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
I guess, I'd favor #1229 over this, agreed ?

**Comment by diabonas** [comment]
Hopefully we can update the Travis build image to Xenial and directly use the packaged version of Doxygen, see #1229 (CI pending).

**Comment by tstruk** [comment]
@diabonas yes, that would be ideal.

**Comment by AndreasFuchsSIT** [comment]
Ok, this was funny... ;-)

**Comment by AndreasFuchsSIT** [comment]
@tstruk the bug in #1226 only occured for the tcti_partial=yes case.
Could it be that some files are activated / deactivated or some macros that mess up doxygen ?

**Comment by tstruk** [comment]
This is a temporary fix for https://github.com/tpm2-software/tpm2-tss/issues/1230
The proper solution is being worked on here https://github.com/tpm2-software/tpm2-tss/pull/1229

**Pull request merged**
