### PR TITLE
[RFC] Add indentprofile

### PR DESCRIPTION
**Pull request by AndreasFuchsTPM**
This is just a little gimmick.
In order to enforce coding guidelines (especially to myself) I added an indent-profile; also to make check.
Also you can use the resulting %.indentlog files directly as patches...

@tstruk : I'd guess that you might like this ?

This is meant as an an RFC

The other two patches remove a problem with indent (; on makro definitions) and give an example...

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
I actually tried to mimic the doc/coding_standard_c.md file as good as I could.
Please go ahead and have a look and tell me what you think is not quite right yet.

**Comment by tstruk** [comment]
@AndreasFuchsSIT it is easy to see by looking at the indent.log.
I think the main difference between the spec implied format and the indent format is the function prototypes, for instance: 
  
-TSS2_RC Tss2_Sys_ClockRateAdjust(
-    TSS2_SYS_CONTEXT *sysContext,
-    TPMI_RH_PROVISION auth,
-    TSS2_SYS_CMD_AUTHS const *cmdAuthsArray,
-    TPM2_CLOCK_ADJUST rateAdjust,
-    TSS2_SYS_RSP_AUTHS *rspAuthsArray)
+TSS2_RC
+Tss2_Sys_ClockRateAdjust(TSS2_SYS_CONTEXT * sysContext,
+                         TPMI_RH_PROVISION auth,
+                         TSS2_SYS_CMD_AUTHS const *cmdAuthsArray,
+                         TPM2_CLOCK_ADJUST rateAdjust,
+                         TSS2_SYS_RSP_AUTHS * rspAuthsArray)

I'm ok with either, but I would like to  get @flihp's opinion on that.

**Comment by tstruk** [comment]
oh, the github formatting messes up the copy and paste terminal format. Indent log attached.
[indent.log](https://github.com/intel/tpm2-tss/files/1515729/indent.log)

**Comment by AndreasFuchsSIT** [comment]
@tstruk you mean the alignment of parameters with the opening ( ?
you can switch this behavior by adding `--dont-line-up-parentheses`.
However this will not only change it for function declarations but also for function invocations, which I hightly dislike. e.g.:
```
     rval = Tss2_Sys_GetEncryptParam(sysContext,
-                                    &currEncryptParamSize,
-                                    &currEncryptParamBuffer);
+        &currEncryptParamSize, &currEncryptParamBuffer);
```
For this and also my personal preference, I prefer lining up function declarations with opening (

**Comment by flihp** [comment]
Hello all. Back from a little time off.

I have no problem modifying our documented coding standard to align with what we can get indent to do for us. I liked the previous function prototype / declaration style mostly because it matched the code from the TPM spec. Let me spend a few minutes with this one today so I can get my head around the scope of the change and side effects etc.

**Comment by AndreasFuchsSIT** [comment]
@flihp @tstruk One question came up here: Do we really want to go to 80 char per line ?

It's quite outdated and we have quite long function names. So the proposal was to go for 100 char per line.

What do you think ?

**Comment by tstruk** [comment]
@AndreasFuchsSIT My opinion is that we should try to limit ourselves to 80 chars per line. This is what the most guide lines recommend.

**Comment by AndreasFuchsSIT** [comment]
@tstruk @flihp Any inputs on the indent-profile ? shall we go for this one or make some changes ?

**Comment by flihp** [comment]
Apologies @AndreasFuchsSIT but I haven't had a chance to spend time on this. @tstruk is also out for the next few weeks unexpectedly and so we're a bit short handed. It may be best to put this PR on "hold" at least until @tstruk is back.

**Comment by tstruk** [comment]
Closing this old PR. The idea about using a tools like indent to check code format is great, but it should just report the issue and not try to fix anything automatically.
I'll create am issue for it.

**Pull request closed without merging**
