### PR TITLE
travis: add ubuntu-20.04 build

### PR DESCRIPTION
**Pull request by tstruk**
Fixes: #1702

### CODE REVIEW

**Comment by tstruk** [comment]
We need one more for Fedora 31. I can build one this week. And I think we could drop ubuntu 18.04. and Fedora 30 then.

**Comment by AndreasFuchsSIT** [comment]
18.04 is an LTS and we should keep it for another year or so.
I'd rather drop 16.04 first... ;-)

**Comment by williamcroberts** [comment]
> We need one more for Fedora 31. I can build one this week. And I think we could
> drop ubuntu 18.04. and Fedora 30 then.

I would drop 16.04, we probably want to keep the last 2 stable things, LTS and what not.
Probably keep fedora 30 and 31, or maybe do 31 and rawhide...

>

**Comment by williamcroberts** [comment]
I guess drop 30, it reached EOL on May 7
  - https://endoflife.date/fedora
  - https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle

Maybe we could do 31 and rawhide, so we can track next as we go.

**Pull request merged**
